#!/usr/bin/env bash
# context.sh — loads JSON config (global + optional per-exercise override)
# and generates the single TCL "context" file that is the sole interface
# between Bash and the TCL task scripts.
# Source only. Depends on: log.sh, jq.

CONFIG_JSON=""   # merged config, set by cfg_init

# cfg_init <assignment> <exercise>
# Merges scripts/config/default.json with an optional
# <assignment>/<exercise>/config.json (exercise values win).
cfg_init() {
    command -v jq >/dev/null 2>&1 || die "jq is required but not installed."

    local assignment="$1" exercise="$2"
    local default_cfg="$REPO_ROOT/scripts/config/default.json"
    local override_cfg="$REPO_ROOT/$assignment/$exercise/config.json"

    [[ -f "$default_cfg" ]] || die "Missing default config: $default_cfg"

    if [[ -f "$override_cfg" ]]; then
        CONFIG_JSON="$(jq -s '.[0] * .[1]' "$default_cfg" "$override_cfg")" \
            || die "Failed to merge config: $override_cfg"
    else
        CONFIG_JSON="$(cat "$default_cfg")"
    fi
}

# cfg_get <jq_filter>
# Prints the raw value at the given jq path from the merged config.
# Prints empty string (not "null") if the path is absent.
cfg_get() {
    jq -r "(${1}) // empty" <<<"$CONFIG_JSON"
}

# resolve_part <board> <explicit_part>
# --part always wins; otherwise --board is looked up in config;
# otherwise falls back to vivado.default_part.
resolve_part() {
    local board="$1" explicit_part="$2"

    if [[ -n "$explicit_part" ]]; then
        printf '%s\n' "$explicit_part"
        return
    fi

    if [[ -n "$board" ]]; then
        local part
        part="$(cfg_get ".vivado.boards[\"$board\"].part")"
        [[ -n "$part" ]] || die "Unknown board '$board' (check scripts/config/default.json)."
        printf '%s\n' "$part"
        return
    fi

    local default_part
    default_part="$(cfg_get '.vivado.default_part')"
    [[ -n "$default_part" ]] || die "No --part/--board given and no vivado.default_part configured."
    printf '%s\n' "$default_part"
}

# write_context <context_file> key=value [key=value ...]
# Writes a flat TCL context file: `set KEY {VALUE}` per line.
# Braces protect against paths containing spaces or special TCL chars.
write_context() {
    local context_file="$1"; shift
    mkdir -p "$(dirname "$context_file")"

    {
        echo "# Auto-generated by run.sh — do not edit by hand."
        for kv in "$@"; do
            local key="${kv%%=*}"
            local val="${kv#*=}"
            printf 'set %s {%s}\n' "$key" "$val"
        done
    } > "$context_file"
}
